on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: npm install tiddlywiki
        run: npm i -g tiddlywiki
      
      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Install python stuff
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install genanki beautifulsoup4

      - name: Build TiddlyWiki
        run: tiddlywiki . --build index

      - name: Generate PDF
        run: |
          wkhtmltopdf \
            --enable-local-file-access \
            --print-media-type \
            --margin-top 15mm \
            --margin-bottom 15mm \
            --margin-left 15mm \
            --margin-right 15mm \
            output/allfiles.html \
            output/allfiles.pdf

      - name: Build anki deck
        run:  |
          python createpkg.py
          mv tiddlywiki.apkg output/MCS.apkg

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4